version: "3.8"

services:
  documentfinder:
    container_name: documentfinder
    build: .
    env_file:
      - .env
    ports:
      - 8742:8742
    command: "uvicorn --host '0.0.0.0' --port 8742 --workers 10 main:app"
    restart: unless-stopped
